### ISSUE TITLE
Input on Windows

### ISSUE THREAD

**Issue by arch-master** [go-ge/goge#1]
The input methods in `extras` need to be windows supported. See [this](https://stackoverflow.com/questions/48082096/user-input-for-a-game-in-go?noredirect=1#comment83139574_48082096).

**Comment by charro** [comment]
Hi there !

I saw that you needed some help, so I forked your repo and added a new pull request with some code that I think could do what you're looking for:

[https://github.com/go-ge/goge/pull/2](https://github.com/go-ge/goge/pull/2)

Cheers !

Miguel
