### ISSUE TITLE
Open source, or simply hosted on github

### ISSUE THREAD

**Issue by bruno-chavez** [go-ge/goge#3]
Hey there noticed your proyect while searching for new stuff to help with, and looking at your readme I think you could need some help with general good practices, as formating using gofmt, generating a godoc and adding a license, stuff that usually helps new people that try to get into a new open source proyect, if you are interested you can check:

https://goreportcard.com/
https://godoc.org/

Im willing to help you with anything if you are interested, and already forked it to try and fiddle with your code, cheers!

**Comment by arch-master** [comment]
Closing...
